In [5]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings("ignore")
import seaborn as sns
import matplotlib.pyplot as plt

# 1.Load the datasets contained in the seaborn library

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df=sns.load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# TASK


In [1]:
from pydataset import data

In [2]:
data()

dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [3]:
df=data("BOD")
df

Time  demand
1     1     8.3
2     2    10.3
3     3    19.0
4     4    16.0
5     5    15.6
6     7    19.8

In [6]:
df1=sns.load_dataset("titanic")

In [7]:
df1

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [18]:
df1.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [21]:
df1.dropna(inplace=True)

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
mi=MinMaxScaler()

In [22]:
x=df1[["age"]]

In [23]:
x

age
1    38.0
3    35.0
6    54.0
10    4.0
11   58.0
..    ...
871  47.0
872  33.0
879  56.0
887  19.0
889  26.0

[182 rows x 1 columns]

In [24]:
x_transformed=minmax.fit_transform(x)

In [25]:
x_transformed

array([[0.46889226],
       [0.43095599],
       [0.67121902],
       [0.0389479 ],
       [0.72180071],
       [0.41831057],
       [0.34243804],
       [0.22862924],
       [0.60799191],
       [0.81031866],
       [0.55741022],
       [0.35508346],
       [0.30450177],
       [0.27921093],
       [0.57005564],
       [0.8861912 ],
       [0.27921093],
       [0.25392008],
       [0.58270106],
       [0.29185635],
       [0.39934244],
       [0.67121902],
       [0.22862924],
       [0.45624684],
       [0.29185635],
       [0.44992413],
       [0.2665655 ],
       [0.75973698],
       [0.69650986],
       [0.62063733],
       [0.00101163],
       [0.02630248],
       [0.5447648 ],
       [0.72180071],
       [0.01365706],
       [0.49418311],
       [0.3803743 ],
       [0.39301973],
       [0.46889226],
       [0.43095599],
       [0.5447648 ],
       [0.45624684],
       [0.35508346],
       [0.7723824 ],
       [0.36772888],
       [0.64592817],
       [0.49418311],
       [0.721

In [26]:
min(x_transformed)

array([0.])

In [27]:
max(x_transformed)

array([1.])

In [30]:
x_transformed.idxmax()

AttributeError: 'numpy.ndarray' object has no attribute 'idxmax'

# standard scaler 

In [31]:
from  sklearn.preprocessing import StandardScaler
st=StandardScaler()

In [32]:
x_fare=df1[["fare"]].values

In [34]:
x_fare_transformed=st.fit_transform(x_fare)

In [35]:
x_fare_transformed

array([[-1.00110129e-01],
       [-3.38484771e-01],
       [-3.54707823e-01],
       [-8.15671915e-01],
       [-6.86542977e-01],
       [-8.64177202e-01],
       [-5.69212621e-01],
       [ 2.41320703e+00],
       [-2.87169016e-02],
       [-2.22082571e-01],
       [ 5.97174125e-02],
       [-8.96951044e-01],
       [-9.34313224e-01],
       [ 2.41320703e+00],
       [-2.32625261e-01],
       [-5.80300668e-01],
       [-2.04003209e-01],
       [-2.13978472e-02],
       [-3.52905262e-01],
       [ 2.21028188e+00],
       [-8.64177202e-01],
       [-2.13978472e-02],
       [-6.90039290e-01],
       [-3.38484771e-01],
       [ 3.67414220e-03],
       [-6.93753222e-01],
       [-1.61506023e-01],
       [-5.95431695e-01],
       [-6.32193458e-01],
       [-6.58193603e-01],
       [-5.23329242e-01],
       [-6.93753222e-01],
       [-6.71194331e-01],
       [ 8.86218655e-01],
       [-8.97442652e-01],
       [-6.28205537e-01],
       [ 4.50381613e-01],
       [-3.44523240e-02],
       [ 1.4

In [36]:
x_fare_transformed.mean()

2.562053133750361e-16

In [37]:
x_transformed.std()

0.197629010698612

In [38]:
data=sns.load_dataset("tips")
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [39]:
data=pd.get_dummies(data)

In [40]:
data

total_bill   tip  size  sex_Male  sex_Female  smoker_Yes  smoker_No  \
0         16.99  1.01     2         0           1           0          1   
1         10.34  1.66     3         1           0           0          1   
2         21.01  3.50     3         1           0           0          1   
3         23.68  3.31     2         1           0           0          1   
4         24.59  3.61     4         0           1           0          1   
..          ...   ...   ...       ...         ...         ...        ...   
239       29.03  5.92     3         1           0           0          1   
240       27.18  2.00     2         0           1           1          0   
241       22.67  2.00     2         1           0           1          0   
242       17.82  1.75     2         1           0           0          1   
243       18.78  3.00     2         0           1           0          1   

     day_Thur  day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0           0        0        0        1           0            1  
1           0        0        0        1           0            1  
2           0        0        0        1           0            1  
3           0        0        0        1           0            1  
4           0        0        0        1           0            1  
..        ...      ...      ...      ...         ...          ...  
239         0        0        1        0           0            1  
240         0        0        1        0           0            1  
241         0        0        1        0           0            1  
242         0        0        1        0           0            1  
243         1        0        0        0           0            1  

[244 rows x 13 columns]

In [41]:
data=pd.get_dummies(data,drop_first=True)

In [42]:
data

total_bill   tip  size  sex_Male  sex_Female  smoker_Yes  smoker_No  \
0         16.99  1.01     2         0           1           0          1   
1         10.34  1.66     3         1           0           0          1   
2         21.01  3.50     3         1           0           0          1   
3         23.68  3.31     2         1           0           0          1   
4         24.59  3.61     4         0           1           0          1   
..          ...   ...   ...       ...         ...         ...        ...   
239       29.03  5.92     3         1           0           0          1   
240       27.18  2.00     2         0           1           1          0   
241       22.67  2.00     2         1           0           1          0   
242       17.82  1.75     2         1           0           0          1   
243       18.78  3.00     2         0           1           0          1   

     day_Thur  day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0           0        0        0        1           0            1  
1           0        0        0        1           0            1  
2           0        0        0        1           0            1  
3           0        0        0        1           0            1  
4           0        0        0        1           0            1  
..        ...      ...      ...      ...         ...          ...  
239         0        0        1        0           0            1  
240         0        0        1        0           0            1  
241         0        0        1        0           0            1  
242         0        0        1        0           0            1  
243         1        0        0        0           0            1  

[244 rows x 13 columns]

In [43]:
data1=sns.load_dataset("tips")

In [46]:
data1=pd.get_dummies(data1,drop_first=True)

In [47]:
data1

total_bill   tip  size  sex_Male  sex_Female  smoker_Yes  smoker_No  \
0         16.99  1.01     2         0           1           0          1   
1         10.34  1.66     3         1           0           0          1   
2         21.01  3.50     3         1           0           0          1   
3         23.68  3.31     2         1           0           0          1   
4         24.59  3.61     4         0           1           0          1   
..          ...   ...   ...       ...         ...         ...        ...   
239       29.03  5.92     3         1           0           0          1   
240       27.18  2.00     2         0           1           1          0   
241       22.67  2.00     2         1           0           1          0   
242       17.82  1.75     2         1           0           0          1   
243       18.78  3.00     2         0           1           0          1   

     day_Thur  day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0           0        0        0        1           0            1  
1           0        0        0        1           0            1  
2           0        0        0        1           0            1  
3           0        0        0        1           0            1  
4           0        0        0        1           0            1  
..        ...      ...      ...      ...         ...          ...  
239         0        0        1        0           0            1  
240         0        0        1        0           0            1  
241         0        0        1        0           0            1  
242         0        0        1        0           0            1  
243         1        0        0        0           0            1  

[244 rows x 13 columns]